### ISSUE TITLE
How to display the CC Type?

### ISSUE THREAD

**Issue by brightonhall** [nogorilla/ng2-cc-library#1]
Yours is the only credit card validation package I've found that actually works in Angular2! 

I have a question, you have a place in the HTML which seems like it's supposed to show the credit card type (Visa, MC, etc.), in...

    [<span class="cc-brand"></span>]
    
... but it doesn't get set when the credit card number is entered.  How can I do this?

And on another note, I found many errors in the demo code when I cloned this.  This is a nice package, but the demo needs fixing.

Here's a list of what I found that needs fixing in the demo:

**app.component.ts**

The following import statement is incorrect...

    import { CreditCardValidator } from '../../src/validators/credit-card.validator';
    
It should be...

    import { CreditCardValidator } from '../../src/credit-card.validator';

**app.html**

The page produces many errors, caused by incorrect form implementations.  It looks like you might have started out using the template method, and then moved to the reactive form method and didn't change all the necessary statements.

Since you are using the FormBuilder functions, (formControlName), the 'form' element needs to change from this...

    <form #demoForm="ngForm" (ngSubmit)="onSubmit(demoForm)" novalidate>
    
... to this.

    <form [formGroup]="demoForm" (ngSubmit)="onSubmit(demoForm)" novalidate>
    
Then in your component, you need to update the variable from `form:FormGroup` to `demoForm:FormGroup`.  The reference variable to create the FormGroup must also be updated.

    this.demoForm = this._fb.group({ ...
    
Then back in the app.html, any reference to the 'form' variable needs to be updated to 'demoForm'.

And lastly in app.html, this line has a typo (expirationDate):

    <div *ngIf="!form.controls.expirationDate.valid" class="alert alert-danger">Expiration Date is required</div>
    
Which should be:

    <div *ngIf="!demoForm.controls.expDate.valid" class="alert alert-danger">Expiration Date is required</div>
    

OK, that being said, this is all just part of the demo and not your actual library which does work very nicely, but a good demo improves your impression with developers.  :^)

**Comment by nogorilla** [comment]
@brightonhall Thanks for the help getting the demo working.

`cc-brand` was not implemented as the intended project no longer needed it. I'll work on adding it back in.

**Comment by brightonhall** [comment]
@nogorilla - yes that would be great if you can add the 'type' feature back in.  I'm using this with the PayPal Api and it requires the credit card type and I don't want the customer to have to choose it.

**Comment by nogorilla** [comment]
@brightonhall the `cc-input` directive adds a card-type class based on the card numbers inputed: `.visa`, `.amex`, etc

**Comment by brightonhall** [comment]
Cool, thanks.  I'll give it a try.

**Comment by nogorilla** [comment]
@brightonhall FYI I renamed the library based on the new angular naming conventions. I've published it with the new name to NPM https://www.npmjs.com/package/angular-cc-library

The old library is still there but will no longer receive new updates
